POST http://localhost:3000/api/users/register
Content-Type: application/json

{
"email":"l@gmail.com",
"password":"12345678"
}

###
POST http://localhost:3000/api/users/validate
Content-Type: application/json

{
"user":"l@gmail.com",
"code":"503146"
}