POST http://localhost:3000/api/users/register
Content-Type: application/json

{
"email":"pa@gmail.com",
"password":"12345678"
}

###
POST http://localhost:3000/api/users/validate
Content-Type: application/json

{
"user":"p@gmail.com",
"code":"541040"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"email":"p@gmail.com",
"password":"12345678"
}


###
PATCH http://localhost:3000/api/storage/logo
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name=image; filename="imagen.jpg"
Content-Type: image/jpeg

< ./imagen.jpg
--boundary123--